In [22]:
import pandas as pd
import numpy as np

In [23]:
leak = pd.read_csv("../leak/clean_leak.csv")
leak.head()

Title  Players Estimate  Steam App ID
0                   Team Fortress 2          50191347           440
1  Counter-Strike: Global Offensive          46305966           730
2     PLAYERUNKNOWN'S BATTLEGROUNDS          36604134        578080
3                          Unturned          27381399        304930
4                     Left 4 Dead 2          23143723           550

In [24]:
appid_list = leak["Steam App ID"].to_numpy()
appid_list

array([   440,    730, 578080, ..., 606500, 629340, 632470], dtype=int64)

In [25]:
from numpy.random import default_rng
rng = default_rng(1339)

rng.shuffle(appid_list)

In [26]:
appid_list

array([354930, 512230, 350210, ..., 230070, 315430,  34030], dtype=int64)

In [27]:
appid_list.size

13228

In [28]:
13228 / 3

4409.333333333333

In [29]:
tasks = np.array_split(appid_list, 3)
tasks

[array([354930, 512230, 350210, ...,  46470, 659190, 326410], dtype=int64),
 array([325880, 545180, 756340, ..., 756380, 547520, 374680], dtype=int64),
 array([455290, 751330, 421670, ..., 230070, 315430,  34030], dtype=int64)]

In [35]:
name = ["zack.txt", "cindy.txt", "sid.txt"]
for path, ids in zip(name, tasks):
    np.savetxt(path, ids, fmt='%i')